package OOResturant;

import java.awt.Color;
import java.awt.Image;
import javax.swing.JOptionPane;
import java.awt.event.WindowEvent;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javafx.scene.layout.Background;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class Login_System extends javax.swing.JFrame {

    /**
     * Creates new form Login_System
     */
    {
        initComponents();
        setIconImage();
        setVisible(true);
    }
    
    public Login_System(String name, String password) {
        jlabErrorPass.setVisible(false);
        jlabErrorName.setVisible(false);
        jLabHide.setVisible(false);
        jtxtPassword.setText(password);
        jtxtUserName.setText(name);
    }
    
    public Login_System() {
        jlabErrorPass.setVisible(false);
        jlabErrorName.setVisible(false);
        jLabHide.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnLogin = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jlabCreate = new javax.swing.JLabel();
        jlabPassword = new javax.swing.JLabel();
        jlabName = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        jlabErrorName = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JPasswordField();
        jlabErrorPass = new javax.swing.JLabel();
        jLabHide = new javax.swing.JLabel();
        jLabShow = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Screen");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 30));

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jbtnLogin.setText("Submit");
        jbtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnLoginMouseExited(evt);
            }
        });
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jbtnReset.setText("Cancel");
        jbtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnResetMouseExited(evt);
            }
        });
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setPreferredSize(new java.awt.Dimension(115, 45));
        jbtnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnExitMouseExited(evt);
            }
        });
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jlabCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabCreate.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdulHameed Mohamed\\Downloads\\add-user (1).png")); // NOI18N
        jlabCreate.setText("Click Here To Create A New Account");
        jlabCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabCreateMouseExited(evt);
            }
        });

        jlabPassword.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jlabPassword.setText("Password:");

        jlabName.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jlabName.setText("UserName:");
        jlabName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabNameMouseEntered(evt);
            }
        });

        jtxtUserName.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jtxtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserNameActionPerformed(evt);
            }
        });
        jtxtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtUserNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtUserNameKeyTyped(evt);
            }
        });

        jlabErrorName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabErrorName.setForeground(new java.awt.Color(255, 0, 0));
        jlabErrorName.setText("Name is Empty !!!");
        jlabErrorName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Warning", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N

        jtxtPassword.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jtxtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPasswordActionPerformed(evt);
            }
        });
        jtxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPasswordKeyTyped(evt);
            }
        });

        jlabErrorPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabErrorPass.setForeground(new java.awt.Color(255, 0, 0));
        jlabErrorPass.setText("Password is Empty !!!");
        jlabErrorPass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Warning", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N

        jLabHide.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdulHameed Mohamed\\Downloads\\lock (1).png")); // NOI18N
        jLabHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabHideMouseClicked(evt);
            }
        });

        jLabShow.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdulHameed Mohamed\\Downloads\\lock.png")); // NOI18N
        jLabShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabShowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlabName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnLogin)
                    .addComponent(jlabPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabErrorPass, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(jLabShow)
                                .addGap(0, 0, 0)
                                .addComponent(jLabHide, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jbtnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabCreate)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabName)
                    .addComponent(jtxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jlabErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabHide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlabPassword)))
                .addGap(0, 0, 0)
                .addComponent(jlabErrorPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLogin)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Resturant Login System");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 10));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdulHameed Mohamed\\Downloads\\login.png")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 10));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdulHameed Mohamed\\Downloads\\login.png")); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)))
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed

        String password = new String(jtxtPassword.getPassword());
        String name = jtxtUserName.getText();
        boolean flagPass = password.equals(""), flagName = name.equals("");
        if (flagName && flagPass) {
            jlabErrorName.setVisible(true);
            jlabErrorPass.setVisible(true);
        } else if (flagName)
            jlabErrorName.setVisible(true);
        else if (flagPass)
            jlabErrorPass.setVisible(true);
        else {
            boolean flag1 = password.equals("0201332483515") && name.equals("AbdulHammed");
            boolean flag2 = password.equals("020133248") && name.equals("Mohamed");
            boolean flag3 = password.equals("020133248") && name.equals("Abeer");
            boolean flag4 = password.equals("020133248") && name.equals("Khadiga");
            boolean flag5 = password.equals("020133248") && name.equals("Hassan");
            boolean flag6 = password.equals("020133248") && name.equals("Abo Baker");
            jtxtUserName.setText("");
            jtxtPassword.setText("");
            if (!(flag1 || flag2 || flag3 || flag4 || flag5 || flag6)) {
                JOptionPane.showMessageDialog(null, "Invalid Login Details", "Login Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String dataAbdo = "I'm a Programming Engineer\nI Like Football And Swimming\nI Love My Family\nMy Family Love Me \nI like Foot\nI am Clever",
                        dataMyFother = "I'm a Survey Engineer\nI Like My Sons And My Family\nMy Family Love Me\nI am good and nervous\nI am religious",
                        datamyMother = "I'm a Science Teacher\nI Love My Sons And My Family\nI Love AbdelHammed\nMy Family Love Me\nI am a Good and Quit",
                        DataHassan = "I'm a King\nI Love My Family\nMy Family Love Me\nI Like Pubj\nI'm a Student\n I am a Single",
                        dataBaker = "I good in Practical Life\nI am a Handsome\nI Love My Family\nMy Family Love Me\nI help with house chores",
                        dataKhadiga = "I'm A Queen To My Family\nI Love My Family And AbdulHameed\nMy Family Love Me\nI'm A Qute\nI Love Foot";
                if (flag1) {
                new Account(name, "Mohamed", "Medo Mashakl", password, "Male", "9/9/1999", dataAbdo, "C:\\Users\\AbdulHameed Mohamed\\Downloads\\abdo.png").setVisible(true);
            } else if (flag2) {
                new Account(name, "Hassan", "El Hag Sahb El Bait", password, "Male", "15/6/1968", dataMyFother, "C:\\Users\\AbdulHameed Mohamed\\Downloads\\manager.png").setVisible(true);
            } else if (flag3) {
                new Account(name, "AbdulHameed", "El Baraka", password, "Female", "3/6/1975", datamyMother, "C:\\Users\\AbdulHameed Mohamed\\Downloads\\woman.png").setVisible(true);
            } else if (flag4) {
                new Account(name, "Mohamed", "The Queen", password, "Female", "15/6/2008", dataKhadiga, "C:\\Users\\AbdulHameed Mohamed\\Downloads\\monarchy.png").setVisible(true);
            } else if (flag5) {
                new Account(name, "Mohamed", "Hassaona El Nagm", password, "Male", "28/6/1998", DataHassan, "C:\\Users\\AbdulHameed Mohamed\\Downloads\\man.png").setVisible(true);
            }
            else {
                new Account(name, "Mohamed", "El Burns", password, "Male", "3/7/2000", dataBaker, "C:\\Users\\AbdulHameed Mohamed\\Downloads\\tennis-player.png").setVisible(true);
            }
                this.dispose();
            }
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    //private JFrame frame;
    
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // frame = new JFrame("Exit");
        String message = "Confirm If You Want To Exit";
        if(!(new String(jtxtPassword.getPassword()).equals("")|| jtxtUserName.getText().equals(""))){
            message = "Warning If You Exit You Lose The Data!\n".concat(message);
        }
        if (JOptionPane.showConfirmDialog(null, message, "Resturant Login System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtUserName.setText("");
        jtxtPassword.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUserNameKeyPressed
        jlabErrorName.setVisible(false);
    }//GEN-LAST:event_jtxtUserNameKeyPressed

    private void jtxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPasswordKeyPressed
        jlabErrorPass.setVisible(false);
    }//GEN-LAST:event_jtxtPasswordKeyPressed

    private void jtxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUserNameActionPerformed

    private void jtxtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUserNameKeyTyped
        Characters(evt);
    }//GEN-LAST:event_jtxtUserNameKeyTyped

    private void jtxtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPasswordKeyTyped

    private void jlabCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabCreateMouseClicked
        new CreateUserAccount().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlabCreateMouseClicked

    private void jLabShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabShowMouseClicked
        jtxtPassword.setEchoChar((char) 0);
        jLabShow.setVisible(false);
        jLabHide.setVisible(true);
    }//GEN-LAST:event_jLabShowMouseClicked

    private void jLabHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabHideMouseClicked
        jtxtPassword.setEchoChar('*');
        jLabHide.setVisible(false);
        jLabShow.setVisible(true);
    }//GEN-LAST:event_jLabHideMouseClicked

    private void jtxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPasswordActionPerformed

    private void jbtnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLoginMouseEntered
        jbtnLogin.setForeground(new Color(235, 235, 235));
        jbtnLogin.setBackground(new Color(251, 192, 45));
    }//GEN-LAST:event_jbtnLoginMouseEntered

    private void jbtnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLoginMouseExited
        jbtnLogin.setForeground(Color.BLACK);
        jbtnLogin.setBackground(new Color(225, 225, 225));
    }//GEN-LAST:event_jbtnLoginMouseExited

    private void jbtnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnResetMouseEntered
        jbtnReset.setForeground(new Color(235, 235, 235));
        jbtnReset.setBackground(new Color(251, 192, 45));
    }//GEN-LAST:event_jbtnResetMouseEntered

    private void jbtnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnResetMouseExited
        jbtnReset.setForeground(Color.BLACK);
        jbtnReset.setBackground(new Color(225, 225, 225));
    }//GEN-LAST:event_jbtnResetMouseExited

    private void jbtnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnExitMouseEntered
        jbtnExit.setForeground(new Color(235, 235, 235));
        jbtnExit.setBackground(new Color(251, 192, 45));
    }//GEN-LAST:event_jbtnExitMouseEntered

    private void jbtnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnExitMouseExited
        jbtnExit.setForeground(Color.BLACK);
        jbtnExit.setBackground(new Color(225, 225, 225));
    }//GEN-LAST:event_jbtnExitMouseExited

    private void jlabCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabCreateMouseEntered
        jlabCreate.setForeground(new Color(254, 156, 19));
        jlabCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 49, 118), 3));
    }//GEN-LAST:event_jlabCreateMouseEntered

    private void jlabCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabCreateMouseExited
        jlabCreate.setForeground(Color.BLACK);
        jlabCreate.setBorder(null);
    }//GEN-LAST:event_jlabCreateMouseExited

    private void jlabNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabNameMouseEntered
        
    }//GEN-LAST:event_jlabNameMouseEntered

    private void jbtnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnExitMouseClicked
        
    }//GEN-LAST:event_jbtnExitMouseClicked

    private void Characters(KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE))) {
            evt.consume();
            getToolkit().beep();
        }
    }

    /**
     * @param args the command line arguments
     */
    public void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("login.png")));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login_System();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabHide;
    private javax.swing.JLabel jLabShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JLabel jlabCreate;
    private javax.swing.JLabel jlabErrorName;
    private javax.swing.JLabel jlabErrorPass;
    private javax.swing.JLabel jlabName;
    private javax.swing.JLabel jlabPassword;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JTextField jtxtUserName;
    // End of variables declaration//GEN-END:variables
//
//private void systemExit(){
//    WindowEvent event = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
//}

}
