/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOResturant;

import javax.swing.JOptionPane;
import java.awt.Component;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.JTextField;
import java.awt.TextField;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JLabel;
import javax.swing.UnsupportedLookAndFeelException;


public class Resturant extends javax.swing.JFrame {

    /**
     * Creates new form Resturant
     */
    Account account;
    public Resturant(Account account) {
        this.account = account;
        initComponents();
        setVisible(true);
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlboTax5 = new javax.swing.JLabel();
        jtxtMeal = new javax.swing.JTextField();
        jtxtDrinks = new javax.swing.JTextField();
        jlboSubTotal5 = new javax.swing.JLabel();
        jlboTotal5 = new javax.swing.JLabel();
        jtxtTotalCost = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnTotal = new javax.swing.JButton();
        jbtnReciept = new javax.swing.JButton();
        jbtnExit1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jlboTax1 = new javax.swing.JLabel();
        jlboSubTotal1 = new javax.swing.JLabel();
        jlboTotal1 = new javax.swing.JLabel();
        jtxtClassicVanilla = new javax.swing.JTextField();
        jtxtVanillaCone = new javax.swing.JTextField();
        jtxtMilkShake = new javax.swing.JTextField();
        jlboTax3 = new javax.swing.JLabel();
        jtxtChocolateMilk = new javax.swing.JTextField();
        jtxtVanillaMilk = new javax.swing.JTextField();
        jlboSubTotal4 = new javax.swing.JLabel();
        jlboTotal4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReciept = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jlboTax2 = new javax.swing.JLabel();
        jlboSubTotal2 = new javax.swing.JLabel();
        jlboTotal2 = new javax.swing.JLabel();
        jtxtChickenLegent = new javax.swing.JTextField();
        jtxtChickenBurger = new javax.swing.JTextField();
        jtxtFish = new javax.swing.JTextField();
        jlboTax4 = new javax.swing.JLabel();
        jlboSubTotal3 = new javax.swing.JLabel();
        jtxtChickenBurgerMeal = new javax.swing.JTextField();
        jtxtBaconAndCheese = new javax.swing.JTextField();
        jlboTotal3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jlboTax = new javax.swing.JLabel();
        jlboSubTotal = new javax.swing.JLabel();
        jlboTotal = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AbdulHameed Mohamed");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));
        jPanel1.setPreferredSize(new java.awt.Dimension(124, 124));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 66)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resturant Managment System");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlboTax5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboTax5.setText("Cost Of Meal");

        jtxtMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtMeal.setEnabled(false);

        jtxtDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDrinks.setEnabled(false);

        jlboSubTotal5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboSubTotal5.setText("Cost Of Drinks");

        jlboTotal5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboTotal5.setText("Total Cost Of Made");

        jtxtTotalCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTotalCost.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlboTotal5)
                    .addComponent(jlboSubTotal5)
                    .addComponent(jlboTax5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtMeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDrinks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTotalCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlboTax5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboSubTotal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlboTotal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 440, 160));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));
        jPanel3.setPreferredSize(new java.awt.Dimension(124, 124));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnReciept.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReciept.setText("Reciept");
        jbtnReciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRecieptActionPerformed(evt);
            }
        });

        jbtnExit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit1.setText("My Account");
        jbtnExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnExit1MouseClicked(evt);
            }
        });
        jbtnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jbtnReciept, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jbtnExit1)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit)
                    .addComponent(jbtnTotal)
                    .addComponent(jbtnReciept)
                    .addComponent(jbtnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 880, 90));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));
        jPanel5.setPreferredSize(new java.awt.Dimension(124, 124));

        jlboTax1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboTax1.setText("Milk Shake");

        jlboSubTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboSubTotal1.setText("Vanilla Cone");

        jlboTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboTotal1.setText("Classic Vanilla");

        jtxtClassicVanilla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtClassicVanilla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtClassicVanilla.setText("0");
        jtxtClassicVanilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtClassicVanillaKeyTyped(evt);
            }
        });

        jtxtVanillaCone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVanillaCone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanillaCone.setText("0");
        jtxtVanillaCone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtVanillaConeKeyTyped(evt);
            }
        });

        jtxtMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMilkShake.setText("0");
        jtxtMilkShake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMilkShakeKeyTyped(evt);
            }
        });

        jlboTax3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlboTax3.setText("Drinks");

        jtxtChocolateMilk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChocolateMilk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChocolateMilk.setText("0");
        jtxtChocolateMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChocolateMilkActionPerformed(evt);
            }
        });
        jtxtChocolateMilk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChocolateMilkKeyTyped(evt);
            }
        });

        jtxtVanillaMilk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVanillaMilk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanillaMilk.setText("0");
        jtxtVanillaMilk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtVanillaMilkKeyTyped(evt);
            }
        });

        jlboSubTotal4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboSubTotal4.setText("Vanilla Milk Shake");

        jlboTotal4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboTotal4.setText("Chockolate Milk Shake");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlboTotal1)
                    .addComponent(jlboSubTotal1)
                    .addComponent(jlboTax1)
                    .addComponent(jlboTotal4)
                    .addComponent(jlboSubTotal4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtClassicVanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtVanillaCone, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtChocolateMilk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtVanillaMilk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlboTax3)
                .addGap(164, 164, 164))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jlboTax3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlboTax1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtVanillaCone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboSubTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtClassicVanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtVanillaMilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboSubTotal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChocolateMilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboTotal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 430, 290));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtReciept.setColumns(20);
        jtxtReciept.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jtxtReciept.setRows(5);
        jtxtReciept.setEnabled(false);
        jScrollPane1.setViewportView(jtxtReciept);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, 450, 560));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlboTax2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboTax2.setText("Filet_O_Fish");

        jlboSubTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboSubTotal2.setText("Chicken Burger");

        jlboTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboTotal2.setText("Chicken Legent");

        jtxtChickenLegent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenLegent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenLegent.setText("0");
        jtxtChickenLegent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChickenLegentKeyTyped(evt);
            }
        });

        jtxtChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurger.setText("0");
        jtxtChickenBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenBurgerActionPerformed(evt);
            }
        });
        jtxtChickenBurger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChickenBurgerKeyTyped(evt);
            }
        });

        jtxtFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFish.setText("0");
        jtxtFish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFishKeyTyped(evt);
            }
        });

        jlboTax4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlboTax4.setText("Meals");

        jlboSubTotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboSubTotal3.setText("Chicken Buger Meal");

        jtxtChickenBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenBurgerMeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurgerMeal.setText("0");
        jtxtChickenBurgerMeal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChickenBurgerMealKeyTyped(evt);
            }
        });

        jtxtBaconAndCheese.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBaconAndCheese.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBaconAndCheese.setText("0");
        jtxtBaconAndCheese.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBaconAndCheeseKeyTyped(evt);
            }
        });

        jlboTotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboTotal3.setText("Bacon And Cheese Burger");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jlboTax4)
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlboSubTotal3)
                            .addComponent(jlboTotal3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtBaconAndCheese, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtChickenBurgerMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlboTax2)
                            .addComponent(jlboSubTotal2)
                            .addComponent(jlboTotal2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtChickenLegent, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtFish, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jlboTax4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboTax2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboSubTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChickenLegent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChickenBurgerMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboSubTotal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBaconAndCheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboTotal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 440, 290));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));
        jPanel8.setPreferredSize(new java.awt.Dimension(124, 124));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTax.setEnabled(false);

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSubTotal.setEnabled(false);

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTotal.setEnabled(false);

        jlboTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboTax.setText("Tax");

        jlboSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboSubTotal.setText("SubTotal");

        jlboTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlboTotal.setText("Total");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlboTax, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlboTax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlboTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 430, 160));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtChocolateMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChocolateMilkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChocolateMilkActionPerformed

    private void jtxtFishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFishKeyTyped
        OnlyNumbers(evt);
    }//GEN-LAST:event_jtxtFishKeyTyped

    private void OnlyNumbers(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        new SubClass_Child().iExitSystem();
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed

        SubClass_Child itemCost = new SubClass_Child();
        double iTax, iSubTotal, iTotal;

        itemCost.filet_O_Fish = itemCost.pFilet_O_Fish * Double.parseDouble(jtxtFish.getText());
        itemCost.chickenBurger = itemCost.pChickenBurger * Double.parseDouble(jtxtChickenBurger.getText());
        itemCost.chickenLegent = itemCost.pChickenLegent * Double.parseDouble(jtxtChickenLegent.getText());
        itemCost.chickenBurgerM = itemCost.pChickenBurgerM * Double.parseDouble(jtxtChickenBurgerMeal.getText());
        itemCost.baconChesseBurger = itemCost.pbaconChesseBurger * Double.parseDouble(jtxtBaconAndCheese.getText());

        itemCost.milkShake = itemCost.pMilkShake * Double.parseDouble(jtxtMilkShake.getText());
        itemCost.vanilleCone = itemCost.pVanilleCone * Double.parseDouble(jtxtVanillaCone.getText());
        itemCost.clasVanilla = itemCost.pClasVanilla * Double.parseDouble(jtxtClassicVanilla.getText());
        itemCost.vanMilkShake = itemCost.pVanMilkShake * Double.parseDouble(jtxtVanillaMilk.getText());
        itemCost.chocMilkShake = itemCost.pChocMilkShake * Double.parseDouble(jtxtChocolateMilk.getText());

        iSubTotal = itemCost.getAmount();
        iTax = itemCost.cFindTax(iSubTotal);
        iTotal = iSubTotal + iTax;

        String subTotal = String.format("$%.2f", iSubTotal);
        jtxtSubTotal.setText(subTotal);

        String total = String.format("$%.2f", iTotal);
        jtxtTotal.setText(total);

        String tax = String.format("$%.2f", iTax);
        jtxtTax.setText(tax);

        String meals = String.format("$%.2f", itemCost.meals);
        jtxtMeal.setText(meals);

        String drink = String.format("$%.2f", itemCost.drink);
        jtxtDrinks.setText(drink);

        String totalCost = String.format("$%.2f", itemCost.totalOfMD);
        jtxtTotalCost.setText(totalCost);

    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnRecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRecieptActionPerformed

        int refs = 1325 + (int) (Math.random() * 4238);

        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyy");
        Tdate.format(timer.getTime());
        jtxtReciept.append("\n\n    Resturant Managment System:"
                + "\n===================================\n"
                + "Reference:\t  " + refs
                + "\n===================================\n"
                + "Meals:\t\t" + jtxtMeal.getText()
                + "\n\nDrinks:\t\t" + jtxtDrinks.getText()
                + "\n\nCost Of Items:\t" + jtxtTotalCost.getText()
                + "\n===================================\n"
                + "Tax:\t\t" + jtxtTax.getText() + "\n\n"
                + "SubTotal:\t" + jtxtSubTotal.getText()
                + "\n\nTotal:\t\t" + jtxtTotal.getText()
                + "\n===================================\n"
                + "Date: " + Tdate.format(timer.getTime())
                + "\nTime: " + tTime.format(timer.getTime())
                + "\n===================================\n"
                + "\t\tThank You");
    }//GEN-LAST:event_jbtnRecieptActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed

        JTextField cleartext = null;
        for (Component c : jPanel7.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                //cleartext = (JTextField) c;
                c = (JTextField) c;
            }
        }

        for (Component c : jPanel5.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("0");
            }
        }

        for (Component c : jPanel4.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("");
            }
        }

        for (Component c : jPanel8.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext = (JTextField) c;
                cleartext.setText("");
            }
        }
        jtxtReciept.setText("");

    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtChickenBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenBurgerActionPerformed

    private void jtxtChickenBurgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChickenBurgerKeyTyped
        OnlyNumbers(evt);
    }//GEN-LAST:event_jtxtChickenBurgerKeyTyped

    private void jtxtChickenLegentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChickenLegentKeyTyped
        OnlyNumbers(evt);
    }//GEN-LAST:event_jtxtChickenLegentKeyTyped

    private void jtxtChickenBurgerMealKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChickenBurgerMealKeyTyped
        OnlyNumbers(evt);
    }//GEN-LAST:event_jtxtChickenBurgerMealKeyTyped

    private void jtxtBaconAndCheeseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBaconAndCheeseKeyTyped
        OnlyNumbers(evt);
    }//GEN-LAST:event_jtxtBaconAndCheeseKeyTyped

    private void jtxtMilkShakeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMilkShakeKeyTyped
        OnlyNumbers(evt);
    }//GEN-LAST:event_jtxtMilkShakeKeyTyped

    private void jtxtVanillaConeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtVanillaConeKeyTyped
        OnlyNumbers(evt);
    }//GEN-LAST:event_jtxtVanillaConeKeyTyped

    private void jtxtClassicVanillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtClassicVanillaKeyTyped
        OnlyNumbers(evt);
    }//GEN-LAST:event_jtxtClassicVanillaKeyTyped

    private void jtxtVanillaMilkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtVanillaMilkKeyTyped
        OnlyNumbers(evt);
    }//GEN-LAST:event_jtxtVanillaMilkKeyTyped

    private void jtxtChocolateMilkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChocolateMilkKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChocolateMilkKeyTyped

    private void jbtnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnExit1ActionPerformed

    private void jbtnExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnExit1MouseClicked
        new Account(account.firstName,account.lastName, account.userName, account.password, account.gender, account.birthDate, account.address, account.image).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnExit1MouseClicked

    /**
     * @param args the command line arguments
     */
    public void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("cloche.png")));
    }

    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {

        /* Create and display the form */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resturant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resturant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resturant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resturant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //UIManager.setLookAndFeel("com.jtatto.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(() -> {
            //new Resturant();
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnExit1;
    private javax.swing.JButton jbtnReciept;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JLabel jlboSubTotal;
    private javax.swing.JLabel jlboSubTotal1;
    private javax.swing.JLabel jlboSubTotal2;
    private javax.swing.JLabel jlboSubTotal3;
    private javax.swing.JLabel jlboSubTotal4;
    private javax.swing.JLabel jlboSubTotal5;
    private javax.swing.JLabel jlboTax;
    private javax.swing.JLabel jlboTax1;
    private javax.swing.JLabel jlboTax2;
    private javax.swing.JLabel jlboTax3;
    private javax.swing.JLabel jlboTax4;
    private javax.swing.JLabel jlboTax5;
    private javax.swing.JLabel jlboTotal;
    private javax.swing.JLabel jlboTotal1;
    private javax.swing.JLabel jlboTotal2;
    private javax.swing.JLabel jlboTotal3;
    private javax.swing.JLabel jlboTotal4;
    private javax.swing.JLabel jlboTotal5;
    private javax.swing.JTextField jtxtBaconAndCheese;
    private javax.swing.JTextField jtxtChickenBurger;
    private javax.swing.JTextField jtxtChickenBurgerMeal;
    private javax.swing.JTextField jtxtChickenLegent;
    private javax.swing.JTextField jtxtChocolateMilk;
    private javax.swing.JTextField jtxtClassicVanilla;
    private javax.swing.JTextField jtxtDrinks;
    private javax.swing.JTextField jtxtFish;
    private javax.swing.JTextField jtxtMeal;
    private javax.swing.JTextField jtxtMilkShake;
    private javax.swing.JTextArea jtxtReciept;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtTotalCost;
    private javax.swing.JTextField jtxtVanillaCone;
    private javax.swing.JTextField jtxtVanillaMilk;
    // End of variables declaration//GEN-END:variables
}
