/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOResturant;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class Setting extends javax.swing.JFrame {

    /**
     * Creates new form Setting
     */
    Account account;

    public Setting(Account account) {
        initComponents();
        this.account = account;
        setVisible(true);
        setLocationRelativeTo(null);
        setSize(445, 730);
        jlablessPass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup = new javax.swing.ButtonGroup();
        jbtnSave = new javax.swing.JButton();
        jbtnSave2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlabTitle = new javax.swing.JLabel();
        jlabIcon1 = new javax.swing.JLabel();
        jlabIcon2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtxtFirst = new javax.swing.JTextField();
        jLabFirst = new javax.swing.JLabel();
        jlabLast = new javax.swing.JLabel();
        jtxtLast = new javax.swing.JTextField();
        jlabUserName = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        jlabPass = new javax.swing.JLabel();
        jtxtPass = new javax.swing.JPasswordField();
        jlabRePass = new javax.swing.JLabel();
        jtxtRePass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jrbMale = new javax.swing.JRadioButton();
        jrbFemale = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAddress = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jtxtImage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtnAccount = new javax.swing.JButton();
        jbtnSaveData = new javax.swing.JButton();
        jlablessPass = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jbtnSave.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jbtnSave.setText("Save Data");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnSave2.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jbtnSave2.setText("Save Data");
        jbtnSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSave2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(446, 742));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jlabTitle.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jlabTitle.setForeground(new java.awt.Color(204, 204, 204));
        jlabTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabTitle.setText("Setting");
        jlabTitle.setPreferredSize(new java.awt.Dimension(250, 61));
        jlabTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabTitleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabTitleMouseExited(evt);
            }
        });

        jlabIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabIcon1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabIcon1MouseExited(evt);
            }
        });

        jlabIcon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabIcon2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabIcon2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jlabIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabIcon2)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jlabIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jlabTitle.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 430, 100);

        jtxtFirst.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtFirst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstActionPerformed(evt);
            }
        });
        jtxtFirst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtFirstKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFirstKeyTyped(evt);
            }
        });

        jLabFirst.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabFirst.setText("FirstName:");

        jlabLast.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jlabLast.setText("LastName:");

        jtxtLast.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtLast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtLast.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtLastKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtLastKeyTyped(evt);
            }
        });

        jlabUserName.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jlabUserName.setText("UserName:");

        jtxtUserName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtUserNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtUserNameKeyTyped(evt);
            }
        });

        jlabPass.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jlabPass.setText("Password:");

        jtxtPass.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPassKeyTyped(evt);
            }
        });

        jlabRePass.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jlabRePass.setText("Retype Pasword:");

        jtxtRePass.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtRePass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtRePass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtRePassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtRePassKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel9.setText("Gender:");

        buttonGroup.add(jrbMale);
        jrbMale.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jrbMale.setText("Male");
        jrbMale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup.add(jrbFemale);
        jrbFemale.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jrbFemale.setText("Female");
        jrbFemale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFemaleActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel10.setText("BirthDate:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel12.setText("Address:");

        jtxtAddress.setColumns(20);
        jtxtAddress.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jtxtAddress.setRows(5);
        jtxtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtAddressKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtxtAddress);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel11.setText("YourImage:");

        jtxtImage.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel4.setText("Attintion:");

        jLabel5.setText("The Address Must Be");

        jLabel6.setText("Less than 80 Characters");

        jbtnAccount.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jbtnAccount.setText("Account");
        jbtnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAccountActionPerformed(evt);
            }
        });

        jbtnSaveData.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jbtnSaveData.setText("Save Data");
        jbtnSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveDataActionPerformed(evt);
            }
        });

        jlablessPass.setForeground(new java.awt.Color(255, 51, 51));
        jlablessPass.setText("Pass Must Be More Than 8 Digit");
        jlablessPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlablessPassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel9)
                            .addGap(143, 143, 143))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlabUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlabPass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlabLast, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(60, 60, 60))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jlabRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtPass)
                                .addComponent(jtxtUserName)
                                .addComponent(jtxtLast)
                                .addComponent(jtxtFirst)
                                .addComponent(jtxtRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jbtnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnSaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jrbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jrbFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtImage))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlablessPass, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtxtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jtxtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlabLast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jlablessPass)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtRePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jrbFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 100, 430, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstActionPerformed

    }//GEN-LAST:event_jtxtFirstActionPerformed

    private void jtxtFirstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFirstKeyPressed

    }//GEN-LAST:event_jtxtFirstKeyPressed
    private void Characters(KeyEvent evt) {
        char c = evt.getKeyChar();
        if ((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
            getToolkit().beep();
        }
    }

    private void jtxtFirstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFirstKeyTyped
        Characters(evt);
    }//GEN-LAST:event_jtxtFirstKeyTyped

    private void jtxtLastKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtLastKeyPressed

    }//GEN-LAST:event_jtxtLastKeyPressed

    private void jtxtLastKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtLastKeyTyped
        Characters(evt);
    }//GEN-LAST:event_jtxtLastKeyTyped

    private void jtxtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUserNameKeyPressed

    }//GEN-LAST:event_jtxtUserNameKeyPressed

    private void jtxtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUserNameKeyTyped
        Characters(evt);
    }//GEN-LAST:event_jtxtUserNameKeyTyped

    private void jtxtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPassKeyPressed
        jlablessPass.setVisible(false);
        jtxtRePass.setEnabled(true);
    }//GEN-LAST:event_jtxtPassKeyPressed

    private void jtxtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPassKeyTyped

    }//GEN-LAST:event_jtxtPassKeyTyped

    private void jtxtRePassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtRePassKeyPressed
        if (jtxtPass.getPassword().length == 0) {
            jtxtRePass.setEnabled(false);
            getToolkit().beep();
        }
        else jtxtRePass.setEnabled(false);
    }//GEN-LAST:event_jtxtRePassKeyPressed

    private void jtxtRePassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtRePassKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRePassKeyTyped

    private void jrbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFemaleActionPerformed

    private int count;
    private void jtxtAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAddressKeyPressed
        char c = evt.getKeyChar();
        if (c != KeyEvent.VK_BACK_SPACE) {
            if (++count > 10) {
                jtxtAddress.setEnabled(false);
                getToolkit().beep();
            }
        } else {
            count--;
            jtxtAddress.setEnabled(true);
        }
    }//GEN-LAST:event_jtxtAddressKeyPressed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed

    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveDataActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are You Sure To Change This Data"
                + "\nConfirm If You Want To Change.", "Resturant Managment System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            jrbMale.setActionCommand("Male");
            jrbFemale.setActionCommand("Female");
            if (!jtxtFirst.getText().equals("")) {
                account.firstName = jtxtFirst.getText();
            }
            if (!jtxtLast.getText().equals("")) {
                account.lastName = jtxtLast.getText();
            }
            if (!jtxtUserName.getText().equals("")) {
                account.userName = jtxtUserName.getText();
            }
            if (jtxtPass.getPassword().length != 0) {
                if (jtxtPass.getPassword().length < 8) {
                    jlablessPass.setVisible(true);
                    return;
                } else if (new String(jtxtPass.getPassword()).equals(new String(jtxtRePass.getPassword()))) {
                    account.password = new String(jtxtPass.getPassword());
                } else {
                    JOptionPane.showMessageDialog(null, "Password Does Not Match!\nPleace Inter Identical Password", "Login System", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if (!buttonGroup.isSelected(null)) {
                account.gender = buttonGroup.getSelection().getActionCommand();
            }
            String birthDate = ((JTextField) jdcBirthDate.getDateEditor().getUiComponent()).getText();
            
            if (!birthDate.isEmpty()) {
                account.birthDate = birthDate;
            }
            
            if (!jtxtAddress.getText().equals("")) {
                account.address = jtxtAddress.getText();
            }
            
            if (!jtxtImage.getText().equals("")) {
                account.image = jtxtImage.getText();
            }
            toAccount();
        } else {
            if (JOptionPane.showConfirmDialog(null, "Are You Need To Go TO Your Account"
                    + "\nConfirm If You Want To go to Account With out Change Setting.", "Resturant Managment System",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                toAccount();
            }
        }
    }//GEN-LAST:event_jbtnSaveDataActionPerformed
    public void toAccount() {
        this.dispose();
        new Account(account.firstName, account.lastName, account.userName, account.password, account.gender, account.birthDate, account.address, account.image);
    }
    private void jbtnSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSave2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSave2ActionPerformed

    private void jbtnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAccountActionPerformed
        toAccount();
    }//GEN-LAST:event_jbtnAccountActionPerformed

    private void jlablessPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlablessPassMouseClicked

    }//GEN-LAST:event_jlablessPassMouseClicked

    private void jlabIcon2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabIcon2MouseEntered
        jlabIcon2.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdulHameed Mohamed\\Downloads\\settings (1).png"));
    }//GEN-LAST:event_jlabIcon2MouseEntered

    private void jlabIcon2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabIcon2MouseExited
        jlabIcon2.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdulHameed Mohamed\\Downloads\\settings.png"));
    }//GEN-LAST:event_jlabIcon2MouseExited

    private void jlabIcon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabIcon1MouseEntered
        jlabIcon1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdulHameed Mohamed\\Downloads\\settings (1).png"));
    }//GEN-LAST:event_jlabIcon1MouseEntered

    private void jlabIcon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabIcon1MouseExited
        jlabIcon1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdulHameed Mohamed\\Downloads\\settings.png"));
    }//GEN-LAST:event_jlabIcon1MouseExited

    private void jlabTitleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabTitleMouseEntered
        jlabTitle.setForeground(new Color(94, 25, 0));
    }//GEN-LAST:event_jlabTitleMouseEntered

    private void jlabTitleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabTitleMouseExited
        jlabTitle.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_jlabTitleMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabFirst;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAccount;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnSave2;
    private javax.swing.JButton jbtnSaveData;
    private javax.swing.JLabel jlabIcon1;
    private javax.swing.JLabel jlabIcon2;
    private javax.swing.JLabel jlabLast;
    private javax.swing.JLabel jlabPass;
    private javax.swing.JLabel jlabRePass;
    private javax.swing.JLabel jlabTitle;
    private javax.swing.JLabel jlabUserName;
    private javax.swing.JLabel jlablessPass;
    private javax.swing.JRadioButton jrbFemale;
    private javax.swing.JRadioButton jrbMale;
    private javax.swing.JTextArea jtxtAddress;
    private javax.swing.JTextField jtxtFirst;
    private javax.swing.JTextField jtxtImage;
    private javax.swing.JTextField jtxtLast;
    private javax.swing.JPasswordField jtxtPass;
    private javax.swing.JPasswordField jtxtRePass;
    private javax.swing.JTextField jtxtUserName;
    // End of variables declaration//GEN-END:variables
}
